// ===== DATA: edit here each day =====
const START = new Date(2026, 8, 6); // Sep 6 2026 (local)

// miles = Rick's pre-trip onX Offroad route for each segment (his true plan; the official Bikepacking Roots figures were 304/326/289/342/250/337/209/344/292 = 2,693). gain = official. days/dates = Rick's plan.
// DO NOT edit miles when he reroutes; put the change on that day's LOG row as course:N instead (negative saved, positive added).
const SEGMENTS = [
  {n:1, from:"Canada (Roosville)", to:"Superior, MT",   miles:296.6, gain:25000, days:7, start:"2026-09-06", end:"2026-09-12", season:"Early Jul to late Sep", seasonState:"ok",    note:"Porcupine Pass, Moon Pass"},
  {n:2, from:"Superior",           to:"Darby, MT",      miles:123.4, gain:3975,  days:3, start:"2026-09-13", end:"2026-09-15", season:"Early Jul to late Sep", seasonState:"ok",    note:"Moose Mountain fire bypass: Alberton, Petty Creek, and down the Bitterroot valley", revised:{on:"2026-09-14", miles:320.5, gain:31000, days:8, end:"2026-09-20", why:"Fire closure. The original line looped west through the Clearwater and back over the Magruder Corridor (125 mi / 14,000 ft); the Moose Mountain Bypass replaces it"}},
  {n:3, from:"Darby",              to:"Mackay, ID",     miles:202.7, gain:12349, days:4, start:"2026-09-16", end:"2026-09-19", season:"Late Jun to late Sep",  seasonState:"tight", note:"Up the West Fork of the Bitterroot, over Horse Creek Pass to the Salmon River, up Panther Creek, then Challis and down US 93 to Mackay", revised:{on:"2026-09-18", miles:348.5, gain:23000, days:7, end:"2026-09-22", why:"Rick's change of plan. Instead of the loop west through Stanley, the Sawtooths, Ketchum and Hailey, he rode from Challis down US 93 to Mackay so he can go home to Idaho Falls for the weekend"}},
  {n:4, from:"Mackay",             to:"Bear Lake (UT line)", miles:341.6, gain:15000, days:7, start:"2026-09-20", end:"2026-09-26", season:"Mid May to late Sep", seasonState:"past", note:"Being redrawn from Mackay by way of Idaho Falls. Miles and dates here are the old Hailey plan until then"},
  {n:5, from:"Bear Lake",          to:"Soldier Summit, UT", miles:250.6, gain:14500, days:6, start:"2026-09-27", end:"2026-10-02", season:"Mid May to late Sep", seasonState:"past", note:""},
  {n:6, from:"Soldier Summit",     to:"Kanab, UT",      miles:334.1, gain:24000, days:8, start:"2026-10-03", end:"2026-10-10", season:"Late Jun to mid Oct",   seasonState:"tight", note:""},
  {n:7, from:"Kanab",              to:"Grand Canyon, AZ", miles:202.6, gain:10000, days:5, start:"2026-10-11", end:"2026-10-15", season:"Mid Apr to late Nov", seasonState:"ok",  note:"Vermilion Cliffs, Kaibab Plateau. Navajo Nation + Babbitt Ranch permits"},
  {n:8, from:"Grand Canyon",       to:"Globe, AZ",      miles:344.9, gain:22000, days:8, start:"2026-10-16", end:"2026-10-23", season:"Early May to late Nov", seasonState:"ok",  note:"AZ State Land recreation permit"},
  {n:9, from:"Globe",              to:"Sierra Vista (MX border)", miles:284.6, gain:21000, days:7, start:"2026-10-24", end:"2026-10-30", season:"Mid Sep to early May", seasonState:"ok", note:""},
];
const TOTAL_PLAN = Math.round(SEGMENTS.reduce((a,s)=>a+s.miles,0)*10)/10;
// Plan calendar, derived from SEGMENTS so a revised segment moves everything after it. Originally 63 days to Nov 7; 58 days to Nov 2 after the Sept 14 segment 2 revision.
const PLAN_DAYS = SEGMENTS.reduce((a,s)=>a+s.days,0);
const PLAN_END = SEGMENTS[SEGMENTS.length-1].end;

// One entry per calendar day. miles = that day's distance. gain/loss in ft. lat/lng = that night's camp (decimal degrees, from Rick's Garmin pin); shown as a Google Maps link in the daily log and the Last camp block.
// Multiple updates in one day: add updates:[{time:"10:30 am", miles:17, gain:370, text:"..."}] (oldest first) and they show grouped under the day's notes.
// course:N on a row = how much a reroute that day changed the length of his course, from the onX segment route with reroutes vs his original. Negative = shortcut (saved miles), positive = detour (added miles). Applied to his position; the plan does not change.
// While he is still riding, set done:false and keep miles/gain at the latest check-in; the row shows "Riding now" and stays out of the completed-day math. When the day ends, remove done:false and fill in end, miles, gain, loss, notes.
const LOG = [
  {day:1, date:"2026-09-06", end:"Loon Lake Campground, MT", miles:60, gain:3761, loss:2838, high:4266, lat:48.59786, lng:-115.67161, notes:"Roosville border to Loon Lake. Big opener with a 4,266 ft high point."},
  {day:2, date:"2026-09-07", end:"Loon Lake Campground, MT", miles:0, gain:0, loss:0, lat:48.59786, lng:-115.67161, notes:"Rain day. Sat tight at camp all day and waited it out."},
  {day:3, date:"2026-09-08", end:"Troy Mine, near Bull Lake, MT", miles:45.6, gain:1749, loss:2895, lat:48.30558, lng:-115.84547, course:-6.8, notes:"Loon Lake to Troy Mine. Mostly downhill to the Kootenai River at 1,884 ft, restocked food in Troy, then south along Hwy 56 to camp near Bull Lake. Took a shortcut that trimmed 6.8 miles off segment 1 (296.6 planned, 289.8 with the reroute)."},
  {day:4, date:"2026-09-09", end:"Porcupine Pass, ID (Montana/Idaho line)", miles:56.5, gain:4431, loss:1876, high:5205, low:2189, lat:47.84681, lng:-115.88983, notes:"Troy Mine to Porcupine Pass. Down Hwy 56 past Bull Lake to the Hwy 200 junction near Noxon, then a 3,000 ft climb from the low point at 2,189 ft to the 5,205 ft pass. Camped ten feet into Idaho. First state down.", updates:[
    {time:"8:30 am", text:"Rolled out after a great night's sleep at the Troy Mine camp."},
    {time:"10:30 am", miles:17, gain:370, text:"Heading south on Hwy 56 toward Cabinet Gorge Reservoir, then he picks up Hwy 200 and keeps going south."},
    {time:"7:20 pm", miles:56.5, gain:4431, text:"Made the Idaho state line at Porcupine Pass and set up camp ten feet into Idaho. Big afternoon climb to the 5,205 ft pass."},
  ]},
  {day:5, date:"2026-09-10", end:"Placer Creek, ID (south of Wallace)", miles:55.4, gain:2936, loss:5273, high:5156, low:2365, lat:47.43047, lng:-115.89064, notes:"Porcupine Pass to Placer Creek. Long descent off the pass into Idaho, 5,156 ft high point at the start to a 2,365 ft low point, water from Shoshone Creek, then down through the Coeur d'Alene National Forest to Wallace for a burger and a shake. Climbed out of town along Placer Creek to camp. Biggest descent day so far, 5,273 ft.", updates:[
    {time:"12:00 pm", miles:16.3, gain:108, text:"Down off Porcupine Pass into Idaho, 2,579 ft of descent to Shoshone Creek at about 2,600 ft. Stopped to fill up with 7 liters of water from the creek."},
    {time:"4:30 pm", miles:45.6, gain:2093, text:"Checked in from Wallace, ID, down out of the Coeur d'Alene National Forest to the town on I-90. Low point of the day was 2,384 ft. Already past the 43 miles he needed today and not done yet."},
    {time:"Evening", miles:55.4, gain:2936, text:"Done for the day at Placer Creek south of Wallace. 55.4 miles, +2,936 / -5,273 ft. Segment 1 ends in Superior on Saturday, 72.3 miles away."},
  ]},
  {day:6, date:"2026-09-11", end:"St Regis River, MT (near DeBorgia)", miles:46.3, gain:6051, loss:6593, high:5074, low:3072, lat:47.37447, lng:-115.36806, course:1.2, notes:"Placer Creek to the St Regis River. Climbed out of camp up Placer Creek over Moon Pass, about 4,900 ft, dropped to 3,072 ft, then spent the afternoon on a rarely used stretch of the Hiawatha rail trail working north toward Taft before turning south. Topped out at 5,074 ft and rolled down the St Regis River to camp near DeBorgia, back in Montana. Biggest climbing day of the trip so far, 6,051 ft up and 6,593 ft down. The Hiawatha loop added 1.2 miles to his course.", updates:[
    {time:"9:20 am", text:"Rolled out from the Placer Creek camp. Got a bath and laundry done last night. Rain overnight, clearing this morning."},
    {time:"11:40 am", miles:12.8, gain:1327, text:"Up Placer Creek to a 4,921 ft high point and down the other side to 3,138 ft. 23.4 more to hit today's share of 36.2."},
    {time:"2:49 pm", miles:27.9, gain:4680, text:"Spent the better part of the afternoon on a rarely used stretch of the Hiawatha rail trail, working north toward Taft, MT before turning back south toward Mexico. Low point 3,021 ft. A big climbing day already at 4,680 ft. 8.3 more to hit today's share."},
    {time:"Evening", miles:46.3, gain:6051, text:"Camped on the St Regis River near DeBorgia, MT. 46.3 miles, +6,051 / -6,593 ft, high point 5,074 ft. Biggest climbing day yet. 27.2 miles to Superior to close out segment 1 tomorrow."},
  ]},
  {day:7, date:"2026-09-12", end:"Hills south of Superior, MT (segment 2, day 1)", miles:69, gain:2767, loss:2661, high:3196, low:2632, lat:47.03492, lng:-114.76697, course:6.3, notes:"Two rides in one day. Morning: 33.5 miles down the St Regis River valley from DeBorgia into Superior, closing out segment 1 on the planned date. Afternoon at the church in town charging power banks and drying gear. Evening: rolled straight into segment 2, 35.5 more miles climbing south out of the Clark Fork valley from 2,718 ft to 3,196 ft, with a short backtrack at the end to find a place to camp after Quartz Flats campground turned out to be closed. Boondocked in a beautiful spot with coyotes yipping and howling all night. 69 miles total, the longest day of the trip so far. His Garmin logged 6.3 more miles through Superior than the segment 1 route measures (riding around town and GPS wander), booked as a 6.3-mile detour so his position stays honest.", updates:[
    {time:"2:07 pm", miles:33.5, gain:1193, text:"Segment 1 is done. Rolled down the St Regis River valley from the DeBorgia camp into Superior, MT, 33.5 miles with 1,193 ft up and 1,514 ft down. Canada to Superior in 7 days, right on the planned date and 6 miles ahead on distance."},
    {time:"Afternoon", text:"Taking a break at the Church of Jesus Christ of Latter-day Saints in Superior to charge every power bank and dry out the tent and clothes. Plan is to roll on this afternoon and put the first miles on segment 2."},
    {time:"Evening", miles:69, gain:2767, text:"Camped in the hills south of Superior after a second ride of 35.5 miles, +1,574 / -1,147 ft, starting segment 2 a day early. Backtracked a little at the end to find a camp spot. 69 miles on the day, a new longest."},
  ]},
  {day:8, date:"2026-09-13", end:"Lolo Creek Campground, MT", miles:39.5, gain:2657, loss:2055, high:4370, low:2903, lat:46.77636, lng:-114.38472, notes:"Whiskey Gulch to Lolo Creek Campground. Out of the hills south of Superior over a 3,249 ft high point and down to the Clark Fork for lunch at the Senior Citizen Center in Alberton, then south up Petty Creek on a long steady climb to a 4,370 ft high point at mile 34 and a short drop to camp on Lolo Creek along Highway 12.", updates:[
    {time:"1:06 pm", miles:19.1, gain:1274, text:"Lunch stop in Alberton, MT at the Senior Citizen Center. Feeling right at home, probably. 19.1 miles so far from the camp south of Superior, up over a 3,249 ft high point out of Whiskey Gulch and down to the Clark Fork. 15.7 more to hit today's share of 34.8."},
    {time:"Evening", miles:39.5, gain:2657, text:"Done at Lolo Creek Campground. 39.5 miles, +2,657 / -2,055 ft, high point 4,370 ft at the top of the Petty Creek climb."},
  ]},
  {day:9, date:"2026-09-14", end:"Hannon Memorial Fishing Access, MT (south of Darby)", miles:73, gain:1094, loss:899, high:3963, low:3164, lat:45.970576, lng:-114.13929, course:19.6, notes:"Lolo Creek to Darby and on to Hannon Memorial Fishing Access on the Bitterroot River, four miles south of town. Segment 2 done three days ahead of the re-timed plan and the first miles of segment 3 in the bank. A cruising day down the valley, dry but chilly with fresh snow on the hills, only 1,094 ft of climbing in 73 miles, which beats the 69 on day 7 for the longest day of the trip. Stocked up on fresh strawberries and Wheat Thins at the Darby grocery store on the way through. His Garmin logged 143 miles through segment 2 against the 123.4-mile bypass route. The route he actually rode measures 128 in onX, so 4.6 of the extra was real detour (the Quartz Flats backtrack) and the other 15 was town riding and GPS overcount. All 19.6 are booked here as a detour to keep his position on the route line.", updates:[
    {time:"12:00 pm", miles:32.4, gain:322, text:"Cruising down the Bitterroot valley. 32.4 miles by midday with only 322 ft of climbing, checked in from Stevensville. Dry so far but chilly, with fresh snow on the hills. About 10 miles to Darby and the end of segment 2."},
    {time:"1:33 pm", miles:47.2, gain:513, text:"47.2 miles by 1:33 pm and going for a single-day mileage record. Darby is 21 miles ahead and he means to get there tonight, which would make it about 68 for the day, right at the 69 he rode on day 7."},
    {time:"4:44 pm", miles:68, gain:998, text:"Made it to Darby. 68 miles from Lolo Creek, +998 / -878 ft, which closes out segment 2 three days ahead of the re-timed plan. Stocking up at the grocery store on fresh strawberries and Wheat Thins, then off to find a camp for the night."},
    {time:"Evening", miles:73, gain:1094, text:"Rode on four miles past town to camp at Hannon Memorial Fishing Access on the Bitterroot River. 73 miles on the day, a new longest, with +1,094 / -899 ft. Segment 3 is under way."},
  ]},
  {day:10, date:"2026-09-15", end:"Spring Creek Campground, ID (Salmon River)", miles:63.3, gain:4805, loss:5358, high:8459, low:3479, lat:45.390811, lng:-114.254899, notes:"Hannon Memorial to Spring Creek Campground on the Salmon River, back in Idaho. Up the West Fork of the Bitterroot past Painted Rocks and Alta on a steady grind, then a brutal summit over Horse Creek Pass at 8,459 ft, the high point of the trip so far by more than 3,000 ft, and two more climbs right after. It was freezing and the wind was ripping, and he did not want to camp on the summit, so he pushed hard to make the long downhill and reached the campground at dark. Squeezed in a plunge in the river at last light, then cheddar broccoli rice and pasta with roasted garlic potatoes. His words: hate going to bed dirty, very uncivilized.", updates:[
    {time:"9:50 am", text:"Rolled out from Hannon Memorial. Took extra time to sort yesterday's grocery haul into days. Coldest morning of the trip so far, but the sun is out and the day looks promising. Hoping for 55 miles."},
    {time:"12:45 pm", miles:27.8, gain:1047, text:"27.8 miles by 12:48 pm with +1,047 / -173 ft, a steady grind up the West Fork of the Bitterroot from 3,965 ft to 4,874 ft. Checked in from West Fork Road just south of Painted Rocks Lake, about three miles north of Alta, near the end of the pavement out of Darby with the dirt climb into the Salmon River Range ahead."},
    {time:"3:40 pm", miles:39.1, gain:1878, text:"39.1 miles with +1,878 / -109 ft, now up to 5,682 ft. Checked in from about seven miles south of Alta, back in the mountains and off the beaten path. His words: having a great time today, new scenery."},
    {time:"5:08 pm", text:"Back in Idaho, over Horse Creek Pass on the Montana line."},
    {time:"8:58 pm", miles:63.3, gain:4805, text:"Long day. A brutal summit over Horse Creek Pass at 8,459 ft and two more ascents right after. Freezing with the wind ripping, so he pushed on rather than camp on top and made the downhill to Spring Creek Campground on the Salmon River. Plunge in the river at last light, dinner on the stove, camp still to finish. 63.3 miles, +4,805 / -5,358 ft."},
  ]},
  {day:11, date:"2026-09-16", end:"Upper Panther Creek, ID (below the Morgan Creek divide)", miles:49, gain:3506, loss:373, high:6529, low:3210, lat:44.90452, lng:-114.32666, notes:"Spring Creek Campground to a camp high on Panther Creek. Down the Salmon River from Shoup to the Panther Creek turnoff, then a long steady climb up the creek from 3,210 ft to 6,529 ft, 49 miles with 3,506 ft of gain and almost no descent. Camped a few miles short of the divide over to Morgan Creek, which sets up the drop toward Challis tomorrow.", updates:[
    {time:"5:16 pm", miles:48.1, gain:3437, text:"Late check-in and still rolling. 48.1 miles from Spring Creek, down the Salmon River and up Panther Creek, climbing from 3,209 ft to 6,453 ft with +3,437 / -373 ft so far. Already past today's share of 40."},
    {time:"Evening", miles:49, gain:3506, text:"Camped high on Panther Creek at about 6,500 ft, a few miles below the divide to Morgan Creek. 49 miles, +3,506 / -373 ft."},
  ]},
  {day:12, date:"2026-09-17", end:"Wagon Wheel Motel, Mackay, ID", miles:88, gain:4316, loss:4957, high:7502, low:4813, lat:43.91756, lng:-113.61678, course:2.6, notes:"Upper Panther Creek to Mackay, 88 miles, the longest day of the trip by 15 miles. Over the top at 7,502 ft first thing, down Morgan Creek to the valley floor at 4,813 ft near Challis, then back up and over into the Big Lost River valley and down to Mackay. +4,316 / -4,957 ft. That finishes segment 3 as revised on Sept 18: Rick skipped the loop through Stanley, the Sawtooths and Hailey to head home to Idaho Falls for the weekend. Spent the night at the Wagon Wheel Motel, his first motel of the trip. His Garmin logged 205.3 miles for the segment against the 202.7-mile route, so the extra 2.6 are booked as a detour.", updates:[
    {time:"Evening", miles:88, gain:4316, text:"Made it to Mackay. 88 miles from Panther Creek, a new longest day by 15 miles, +4,316 / -4,957 ft with a 7,502 ft high point first thing in the morning. First motel night of the trip, at the Wagon Wheel."},
  ]},
];

// Rick's last known position. This drives the "Where is Rick?" block, the map, and the weather. Update whenever new coordinates come in, even mid-day.
// town = nearest town, state = 2-letter state, label = extra detail (forest, lake, pass), asOf = when the position was reported (Mountain time), approx:true shows an "approximate" tag instead of "from his Garmin".
const LOCATION = {lat:43.91756, lng:-113.61678, town:"Mackay", state:"ID", label:"At the Wagon Wheel Motel in Mackay after 88 miles on day 12, his first motel night of the trip (pin from the motel address)", asOf:"Sept 17, evening MT", approx:true};

// Intraday news that is not a completed day. Shows under the position. Set to "" when there is nothing to say. Only add a LOG row once the day is done.
const STATUS = "Plan change, Sept 18: Rick is going home to Idaho Falls for the weekend to sleep in his own bed and go to church on Sunday, heading back out Monday. Segment 3 now ends in Mackay instead of Hailey, 202.7 miles over the West Fork of the Bitterroot, Horse Creek Pass, Panther Creek and down US 93, and he finished it on day 12 with an 88-mile day, his longest yet, then took his first motel night of the trip at the Wagon Wheel in Mackay. Segment 4 from Mackay is being redrawn.";
// Cover photo for the top of the tracker page (file name without .jpg, from rick/photos/). Use a wide crop; the bottom third fades into the page.
// Zoomed-out map of the whole West with Rick's track so far (screenshot from the Windy/onX view). Re-shoot every few days, overwrite the same file, update asOf.
const PROGRESS_MAP = {file:"wwr-progress-map", asOf:"Sept 16, 2026, end of day 11", caption:"Blue and green at the top is Rick's track so far, Roosville to upper Panther Creek in central Idaho, with today's ride in green. The route runs south through Idaho, Utah and Arizona to the Mexican border at Sierra Vista."};
const COVER = "2026-09-06-roosville-start-cover";

// Photos: file names live in rick/photos/. Add the full-size jpg plus a -thumb.jpg. Newest first.
const PHOTOS = [
  {file:"2026-09-18-arco-submarine", date:"2026-09-18", time:"09:56", caption:"Day 13. Arco, Idaho, the Submarine in the Desert: the sail of the USS Hawkbill, SSN-666, on display in town, a long way from any ocean. Arco was also the first town in the world lit by nuclear power, in 1955."},
  {file:"2026-09-17-lost-river-range", date:"2026-09-17", time:"17:17", caption:"Day 12. The bike on US 93 with fresh snow on the Lost River Range, on the way down the Big Lost River valley to Mackay."},
  {file:"2026-09-17-canyon-road-to-challis", date:"2026-09-17", time:"11:03", caption:"Day 12. A gravel road through a rocky canyon on the way down toward Challis."},
  {file:"2026-09-17-panther-creek-breakfast", date:"2026-09-17", time:"07:55", caption:"Day 12. Breakfast at the Panther Creek camp, headlamp still on, with a fellow camper at the stove behind."},
  {file:"2026-09-17-panther-creek-camp-morning", date:"2026-09-17", time:"07:39", caption:"Day 12, morning. Packing up the camp high on Panther Creek before the 88-mile day to Mackay."},
  {file:"2026-09-16-salmon-river-bridge", date:"2026-09-16", time:"09:55", caption:"Day 11. The bike on a bridge over the Salmon River near Shoup, the canyon walls lit up behind."},
  {file:"2026-09-16-shoup-store-selfie", date:"2026-09-16", time:"09:46", caption:"Day 11. At the old Shoup Store on the Salmon River, bundled up for a cold morning."},
  {file:"2026-09-16-spring-creek-camp", date:"2026-09-16", time:"07:38", caption:"Day 11, morning. Camp at Spring Creek Campground on the Salmon River after the Horse Creek Pass day."},
  {file:"2026-09-15-ridge-after-horse-creek-pass", date:"2026-09-15", time:"17:41", caption:"Day 10. The loaded bike on a ridgetop after Horse Creek Pass, back in Idaho with two more climbs to go before the Salmon River."},
  {file:"2026-09-15-horse-creek-pass-climb", date:"2026-09-15", time:"16:58", caption:"Day 10. High on the Horse Creek Pass climb, old burn scars on the slopes and the Idaho line just ahead."},
  {file:"2026-09-15-painted-rocks-fire-station", date:"2026-09-15", time:"12:56", caption:"Day 10. At the Painted Rocks Fire and Rescue station on the West Fork of the Bitterroot, about 28 miles into the day."},
  {file:"2026-09-15-grocery-haul-sorted", date:"2026-09-15", time:"07:02", caption:"Day 10, morning. The Darby grocery haul laid out on the picnic table at Hannon Memorial and sorted into days before rolling out."},
  {file:"2026-09-14-light-of-the-valley-sign", date:"2026-09-14", time:"11:36", caption:"Day 9. Seemed extremely appropriate!!! (Light of the Valley Assembly of God, Bitterroot valley: If your life stinks we have a pew for you.)", by:"rick"},
  {file:"2026-09-13-petty-creek-view", date:"2026-09-13", time:"15:26", caption:"Day 8. Looking back down Petty Creek valley before descending to Lolo Creek.", by:"rick"},
  {file:"2026-09-13-pavement-ends-selfie", date:"2026-09-13", time:"14:36", caption:"Day 8. Headed up Petty Creek valley to the Lolo Creek valley.", by:"rick"},
  {file:"2026-09-12-camp-south-of-superior", date:"2026-09-12", time:"18:59", caption:"Day 7, evening. Boondocked here after finding out Quartz Flats campground was closed. Ended up being a beautiful spot. Coyotes yipped and howled all night.", by:"rick"},
  {file:"2026-09-12-church-plaque-selfie", date:"2026-09-12", time:"13:55", caption:"Day 7. LDS church in Superior MT where I stopped for an extended lunch to recharge battery banks and dry wet laundry from two days ago!", by:"rick"},
  {file:"2026-09-12-laundry-on-the-church-fence", date:"2026-09-12", time:"13:51", caption:"Day 7. Laundry drying on the fence at the church in Superior while the power banks charge."},
  {file:"2026-09-12-superior-exit-sign-selfie", date:"2026-09-12", time:"12:30", caption:"Day 7. 1 mile to the finish line... of segment 1! 8 more segments to go!!", by:"rick"},
  {file:"2026-09-12-bikepackers-on-the-road", date:"2026-09-12", time:"10:14", caption:"Day 7. Crossed paths with Dave and Betsy. Bikepacking from Yellowstone to Seattle.", by:"rick"},
  {file:"2026-09-11-st-regis-river-dinner", date:"2026-09-11", time:"18:39", caption:"Day 6. Dinner on the bank of the St Regis River near DeBorgia: Mountain House Mexican rice and chicken on the MSR stove, with a tortilla on the side."},
  {file:"2026-09-11-st-regis-river-camp", date:"2026-09-11", time:"18:35", caption:"Day 6. Camp set up on the banks of the St Regis river and river front dining. Adobo rice and chicken tacos. Everything tastes better wrapped in tortillas!!", by:"rick"},
  {file:"2026-09-11-waterfall-selfie", date:"2026-09-11", time:"15:19", caption:"Day 6. Waterfall just before the last long tunnel on the Hiawatha.", by:"rick"},
  {file:"2026-09-11-tuna-wrap-lunch", date:"2026-09-11", time:"14:35", caption:"Day 6. Trail lunch at a picnic table: tuna salad in a tortilla, cut with the Gerber."},
  {file:"2026-09-11-1910-fires-sign", date:"2026-09-11", time:"13:32", caption:"Day 6. The 1910 Fires interpretive sign on the Hiawatha rail trail. The Big Burn swept three million acres of Idaho and Montana in two days, including the valley behind the sign."},
  {file:"2026-09-11-bike-on-trestle", date:"2026-09-11", time:"12:57", caption:"Day 6. The loaded bike on one of the Hiawatha rail trail trestles, the Bitterroots stacked up behind."},
  {file:"2026-09-11-trestle-looking-down", date:"2026-09-11", time:"12:57", caption:"Day 6. Looking straight down off a Hiawatha trestle at the steel and the forest a long way below."},
  {file:"2026-09-11-hiawatha-tunnel", date:"2026-09-11", time:"12:20", caption:"Day 6. One of the old Milwaukee Road tunnels on the Hiawatha rail trail, daylight at the far end."},
  {file:"2026-09-11-hiawatha-sign-selfie", date:"2026-09-11", time:"12:09", caption:"Day 6. Route of the Hiawatha Rail Trail (where you thought I missed a turn!)", by:"rick"},
  {file:"2026-09-11-trestle-across-the-valley", date:"2026-09-11", time:"13:12", caption:"Day 6. From one Hiawatha trestle, looking across the valley to the next one."},
  {file:"2026-09-11-hiawatha-trailhead-gate", date:"2026-09-11", time:"12:16", caption:"Day 6. The timber gate at the Route of the Hiawatha trailhead."},
  {file:"2026-09-11-burned-meadow-snags", date:"2026-09-11", time:"11:37", caption:"Day 6. Old snags standing over a meadow on the way up from Placer Creek, leftovers from the 1910 burn that the trail signs describe."},
  {file:"2026-09-11-leaning-snag", date:"2026-09-11", time:"11:30", caption:"Day 6. Fire snags from the Great Fire of 1910.", by:"rick"},
  {file:"2026-09-11-high-point-view", date:"2026-09-11", time:"10:57", caption:"Day 6. The view from near the first high point of the day, ridges stacked into the haze."},
  {file:"2026-09-11-tall-pines-valley-view", date:"2026-09-11", time:"10:47", caption:"Day 6. Tall pines on the climb out of Placer Creek, the valley opening up behind them."},
  {file:"2026-09-11-larch-forest-climb", date:"2026-09-11", time:"10:47", caption:"Day 6. Views from the top of Moon Pass.", by:"rick"},
  {file:"2026-09-11-placer-creek-camp-morning", date:"2026-09-11", time:"07:50", caption:"Day 6, morning. Camp just south of Wallace. Little creek nearby. Took a bath and did laundry.", by:"rick"},
  {file:"2026-09-10-great-fire-1910-sign", date:"2026-09-10", time:"17:38", caption:"Day 5, evening. The Great Fire of 1910 sign at Placer Creek, near camp. In August 1910 the fire swept this drainage; Ranger Ed Pulaski led his crew of 45 into an abandoned mine tunnel about two miles up the West Fork of Placer Creek and saved 40 of them."},
  {file:"2026-09-10-wallace-berry-shake", date:"2026-09-10", time:"15:55", caption:"Day 5. Berry shake in Wallace, the reward after the bacon burger."},
  {file:"2026-09-10-wallace-burger", date:"2026-09-10", time:"16:02", caption:"Day 5. Lunch in Wallace, ID: bacon burger, sweet potato fries, and a berry shake."},
  {file:"2026-09-10-mossy-bank", date:"2026-09-10", time:"10:30", caption:"Day 5. A mossy bank and spring beside the road on the descent from Porcupine Pass, seen from the saddle."},
  {file:"2026-09-10-food-inventory", date:"2026-09-10", time:"08:24", caption:"Day 5. Food inventory laid out on the ground next to the pannier, counting what is left."},
  {file:"2026-09-10-mossy-spring", date:"2026-09-10", time:"10:30", caption:"Day 5. Mossy rock face with a spring trickling down it on the descent from Porcupine Pass toward Wallace."},
  {file:"2026-09-09-porcupine-pass-night-camp", date:"2026-09-09", time:"22:07", caption:"Day 4, 10 pm. Camp on Porcupine Pass by headlamp: tent up, clothes on the line, first night in Idaho."},
  {file:"2026-09-09-porcupine-pass-evening-view", date:"2026-09-09", time:"18:56", caption:"Day 4, evening. The view from the Porcupine Pass camp on the Idaho line, ridges fading into the haze at sunset."},
  {file:"2026-09-09-kootenai-sign-selfie", date:"2026-09-09", time:"12:47", caption:"Day 4, midday. Rick at the Kootenai National Forest sign, dried out and heading south for the Idaho line."},
  {file:"2026-09-09-troy-mine-camp", date:"2026-09-09", time:"07:42", caption:"Day 4, morning. Camp near Troy Mine: tent under the firs, bike leaned up, gear spread out on the tarp to dry, and food bags hung in the trees."},
  {file:"2026-09-09-porcupine-pass-sign-selfie", date:"2026-09-09", time:"16:21", caption:"Day 4, late afternoon. Rick at the Porcupine Pass 9 / State Line 9 sign on the Montana side, nine miles below the pass with the climb still ahead, loaded bike behind him."},
  {file:"2026-09-09-day4-ride-map", date:"2026-09-09", caption:"Day 4 route on onX Offroad: Troy Mine to Porcupine Pass on the Idaho border, 56.5 mi, +4,431 / -1,876 ft. Green is the day, purple is the plan."},
  {file:"2026-09-08-kootenai-bridge", date:"2026-09-08", time:"14:52", caption:"Day 3. Old steel truss bridge over the Kootenai River near Troy, MT, on the way to camp at Troy Mine."},
  {file:"2026-09-08-downed-tree", date:"2026-09-08", time:"13:14", caption:"Day 3. First obstacle of the trip: a fresh blowdown across the road below a rock slide."},
  {file:"2026-09-08-selfie-fog", date:"2026-09-08", time:"11:24", caption:"Day 3. Wet but smiling, fog hanging in the trees on the road south from Loon Lake."},
  {file:"2026-09-08-handlebar-view-fog", date:"2026-09-08", time:"11:23", caption:"Day 3. Handlebar view on the road south from Loon Lake, clouds lifting off the valley after two days of rain."},
  {file:"2026-09-08-tent-interior", date:"2026-09-08", time:"08:48", caption:"Day 3, morning. Inside the tent at Loon Lake after the rain day: camp chair, dry bags, and the wet fly, packing up to ride."},
  {file:"2026-09-08-day3-ride-map", date:"2026-09-08", caption:"Day 3 route on onX Offroad: Loon Lake Campground to Troy Mine, 45.6 mi, +1,749 / -2,895 ft. Green is the day, purple is the plan."},
  {file:"2026-09-07-bear-hang", date:"2026-09-07", time:"19:35", caption:"Day 2. Food bag hung high in the cedars for the second night at Loon Lake. Grizzly country."},
  {file:"2026-09-07-loon-lake-lily-pads", date:"2026-09-07", time:"19:31", caption:"Day 2, evening. Loon Lake under low clouds, lily pads on the water, the rain finally easing."},
  {file:"2026-09-07-loon-lake-camp", date:"2026-09-07", time:"19:30", caption:"Day 2, evening. Camp at Loon Lake Campground at the end of the rain day: tent up, helmet on the picnic table, rain gear hung on a tree to drip."},
  {file:"2026-09-06-day1-ride-map", date:"2026-09-06", caption:"Day 1 route on onX Offroad: Roosville to Loon Lake Campground, 60 mi, +3,761 / -2,838 ft, 4,266 ft high point."},
  {file:"2026-09-06-koocanusa-bridge", date:"2026-09-06", time:"13:36", caption:"Day 1. The Lake Koocanusa bridge from the road above, the longest bridge in Montana, over the Kootenai River backed up behind Libby Dam."},
  {file:"2026-09-06-roosville-start", date:"2026-09-06", time:"10:02", caption:"Day 1. Rick and the loaded bike at the Roosville border crossing, ready to roll south."},
];
const LAST_UPDATED = "Sept 19, 2026, 7:10 am MT";
// ===== END DATA =====
