-- Dance Flowers: orders schema. Paste the whole file into the Supabase SQL editor and run it.
-- Safe to re-run: every statement is create-or-replace / if-not-exists.

-- Products: server-side source of truth for prices. The page keeps its own display copy.
create table if not exists public.products (
  key         text primary key,                 -- corsage | boutonniere | bouquet
  label       text not null,
  price       numeric(8,2) not null check (price >= 0),
  active      boolean not null default true,
  sort        int not null default 0
);
insert into public.products (key, label, price, sort) values
  ('corsage',     'Corsage',     25, 1),
  ('boutonniere', 'Boutonnière', 15, 2),
  ('bouquet',     'Bouquet',     35, 3)
on conflict (key) do nothing;

-- Orders.
create table if not exists public.orders (
  id              uuid primary key default gen_random_uuid(),
  order_number    int  generated by default as identity (start with 1001) unique,
  public_token    uuid not null default gen_random_uuid(),   -- lets the confirmation page mark "payment sent" for this order only
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  status          text not null default 'new'
                  check (status in ('new','confirmed','payment_sent','paid','ready','picked_up','cancelled')),
  items           jsonb not null,            -- {"corsage":2,"boutonniere":1}
  total           numeric(8,2) not null,     -- computed server-side from products
  event_type      text not null,
  event_date      date not null,
  colors          text,
  name            text not null,
  phone           text not null,
  email           text,
  notes           text,
  page            text,
  ua              text,
  payment_sent_at timestamptz,
  paid_at         timestamptz,
  internal_notes  text                        -- Leah's private notes, never shown to the customer
);
create index if not exists orders_status_idx on public.orders (status, event_date);
create index if not exists orders_created_idx on public.orders (created_at desc);

-- Keep updated_at fresh.
create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;
drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
  for each row execute function public.set_updated_at();

-- Lock the tables down. The public site never touches them directly; it goes through the two functions below.
alter table public.products enable row level security;
alter table public.orders   enable row level security;
revoke all on public.orders   from anon;
revoke all on public.products from anon;

-- Anyone may read the product list (used later if the page wants live prices).
drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select to anon, authenticated using (active);
grant select on public.products to anon;

-- Signed-in staff (Leah, Shawn) can read and update orders. Signups are disabled in Auth settings, so
-- "authenticated" means an account one of us created on purpose.
drop policy if exists "staff read orders"   on public.orders;
drop policy if exists "staff update orders" on public.orders;
create policy "staff read orders"   on public.orders for select to authenticated using (true);
create policy "staff update orders" on public.orders for update to authenticated using (true) with check (true);
grant select, update on public.orders to authenticated;
grant all on public.products to authenticated;

-- place_order: called by the public page. Validates, prices the items itself, inserts, and returns
-- what the confirmation panel needs. Runs as the table owner so anon needs no table rights.
create or replace function public.place_order(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_items   jsonb := coalesce(payload->'items', '{}'::jsonb);
  v_total   numeric(8,2) := 0;
  v_count   int := 0;
  r         record;
  v_qty     int;
  v_row     public.orders;
begin
  -- Price every requested item from the products table; ignore unknown keys.
  for r in select key, price from public.products where active loop
    v_qty := coalesce((v_items->>r.key)::int, 0);
    if v_qty < 0 or v_qty > 50 then raise exception 'Quantity out of range for %', r.key; end if;
    v_total := v_total + v_qty * r.price;
    v_count := v_count + v_qty;
  end loop;
  if v_count = 0 then raise exception 'Add at least one item'; end if;

  if coalesce(trim(payload->>'name'), '')       = '' then raise exception 'Name is required'; end if;
  if coalesce(trim(payload->>'phone'), '')      = '' then raise exception 'Phone is required'; end if;
  if coalesce(trim(payload->>'event_type'), '') = '' then raise exception 'Event is required'; end if;
  if (payload->>'event_date') is null              then raise exception 'Event date is required'; end if;

  insert into public.orders (items, total, event_type, event_date, colors, name, phone, email, notes, page, ua)
  values (
    v_items, v_total,
    left(trim(payload->>'event_type'), 60),
    (payload->>'event_date')::date,
    left(payload->>'colors', 2000),
    left(trim(payload->>'name'), 120),
    left(trim(payload->>'phone'), 40),
    nullif(left(trim(payload->>'email'), 200), ''),
    left(payload->>'notes', 2000),
    left(payload->>'page', 300),
    left(payload->>'ua', 400)
  )
  returning * into v_row;

  return jsonb_build_object(
    'order_number', v_row.order_number,
    'token',        v_row.public_token,
    'total',        v_row.total,
    'name',         v_row.name
  );
end $$;

-- mark_payment_sent: the confirmation page's "I sent my Venmo" button. Needs the order's own token.
create or replace function public.mark_payment_sent(p_order_number int, p_token uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare v_n int;
begin
  update public.orders
     set status = 'payment_sent', payment_sent_at = now()
   where order_number = p_order_number and public_token = p_token
     and status in ('new','confirmed');
  get diagnostics v_n = row_count;
  return v_n = 1;
end $$;

revoke all on function public.place_order(jsonb) from public;
revoke all on function public.mark_payment_sent(int, uuid) from public;
grant execute on function public.place_order(jsonb) to anon, authenticated;
grant execute on function public.mark_payment_sent(int, uuid) to anon, authenticated;
